config/routes.rb
Rails.application.routes.draw do
  root "tournaments#index"

  resources :tournaments, only: [:index, :new, :create, :show]
  resources :tournament_division_results, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/concerns/tournament/tournament_callbacks.rb
class Tournament < ApplicationRecord
  module TournamentCallbacks
    extend ActiveSupport::Concern

    included do
      after_save :create_tournament_divisions
    end

    private

      def create_tournament_divisions
        teams.shuffle.each_slice(SOFT_SETTINGS["teams_number"] / SOFT_SETTINGS["divisions_number"]) do |division_teams|
          TournamentDivision.create(teams: division_teams, tournament: self)
        end
      end
  end
end

app/models/concerns/tournament_division_result/tournament_division_result_callbacks.rb
class TournamentDivisionResult < ApplicationRecord
  module TournamentDivisionResultCallbacks
    extend ActiveSupport::Concern

    included do
      after_save :generate_results
    end

    private

      def generate_results
        division_teams = tournament_division.teams

        teams_rating_hash = division_teams.each_with_object(Hash.new(0)) do |t, hash|
          division_teams.each do |i|
            next if i == t
            hash[[t, i].sample] += 1
          end
        end.sort_by { |k,v| -v }.to_h

        teams_rating_hash.first(4).each do |team,score|
          TeamsTournamentDivisionResult.create(team: team, score: score, tournament_division_result_id: self.id)
        end
      end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :tournaments
  has_and_belongs_to_many :tournament_divisions
  has_and_belongs_to_many :tournament_division_results
  has_one :teams_tournament_division_result

  def score
    teams_tournament_division_result.score
  end
end

app/models/teams_tournament_division_result.rb
class TeamsTournamentDivisionResult < ApplicationRecord
  self.table_name = "teams_tournament_division_results"
  default_scope { order(team_id: :desc) }

  belongs_to :team
  belongs_to :tournament_division_result
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  include TournamentCallbacks

  has_and_belongs_to_many :teams
  has_many :tournament_divisions

  accepts_nested_attributes_for :teams

  def first_division
    tournament_divisions.order(:id).first
  end

  def second_division
    tournament_divisions.order(:id).second
  end

  def division_results(number)
    send("#{number}_division").tournament_division_result
                              &.teams
                              &.joins(:teams_tournament_division_results)
                              &.order("teams_tournament_division_results.score DESC")
  end

  def play_off
    teams.joins(:teams_tournament_division_results).order(score: :DESC)
  end

  def winner
  end
end

app/models/tournament_division.rb
class TournamentDivision < ApplicationRecord
  belongs_to :tournament
  has_and_belongs_to_many :teams
  has_one :tournament_division_result
end

app/models/tournament_division_result.rb
class TournamentDivisionResult < ApplicationRecord
  include TournamentDivisionResultCallbacks

  has_and_belongs_to_many :teams
  belongs_to :tournament_division
  has_one :teams_tournament_division_result
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tournament_division_results_controller.rb
class TournamentDivisionResultsController < ApplicationController
  def create
    @tournament_division = TournamentDivision.find_by(id: params[:tournament_division_id])

    if TournamentDivisionResult.create(tournament_division: @tournament_division)
      flash[:suceess] = "Results generated successfully"
    else
      flash[:suceess] = "Results were not generated due to some reason"
    end

    redirect_to tournament_path(@tournament_division.tournament)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all.order(created_at: :DESC)
  end

  def new
    @tournament = Tournament.new
    SOFT_SETTINGS["teams_number"].times { @tournament.teams.build }
  end

  def create
    @tournament = Tournament.new(tournaments_params)

    if @tournament.save
      flash[:success] = "Tournament successfully created"
     redirect_to tournament_path(@tournament)
    else
     render :new
    end
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  private

    def tournaments_params
      params.require(:tournament).permit(:title, teams_attributes: [:id, :title])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tournament
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      - flash.each do |key, value|
        %div{class: "#{flash_class(key)}"}
          = value
      = yield

app/views/tournaments/index.html.haml
- if @tournaments.any?
  = link_to "Create new", new_tournament_path
  - @tournaments.each do |tournament|
    = link_to tournament do
      .jumbotron.jumbotron-fluid
        .container
          %h1.display-4=tournament.title
- else
  .alert.alert-warning{role: "alert"}
    No tournaments found. Create
    = link_to "new", new_tournament_path

app/views/tournaments/new.html.haml
= form_for @tournament do |f|
  %label Tournament Title
  = f.text_field :title
  %hr
  = f.fields_for :teams do |f|
    %div
      %label Team Title
      = f.text_field :title
  %hr
  = f.submit "Create tournament"

app/views/tournaments/show.html.haml
%h2= @tournament.title

%hr
.row
  .col
    %p
      %i Division A
    %hr
    - @tournament.first_division.teams.each do |team|
      %p= team.title

    - if @tournament.division_results("first")
      %hr
      %p
      %i Division A results
      %hr
      - @tournament.division_results("first").each do |team|
        %p #{team.title} - #{team.score}
    - else
      = link_to "Generate Division A results", tournament_division_results_path(tournament_division_id: @tournament.first_division.id), method: :post

  .col
    %p
      %i Division B
    %hr
    - @tournament.second_division.teams.each do |team|
      %p= team.title

    - if @tournament.division_results("second")
      %hr
      %p
      %i Division B results
      %hr

      - @tournament.division_results("second").each do |team|
        %p #{team.title} - #{team.score}
    - else
      = link_to "Generate Division B results", tournament_division_results_path(tournament_division_id: @tournament.second_division.id), method: :post
%hr
%p
  %i Play-off
%hr
- if @tournament.division_results("first") && @tournament.division_results("second")
  - play_off = @tournament.play_off.pluck(:title)
  - 4.times do
    %p #{play_off.shift} - #{play_off.pop}

%hr
%p
  %i Winner
%hr
= @tournament.winner